config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
  sessions:      'admins/sessions'
  # passwords:     'admins/passwords',
  # registrations: 'admins/registrations'
}
devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  # passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}


  namespace :public do
    resources :addresses
    resources :orders
    resources :cart_items
    resource :customers
    resources :items
    post 'confirmation' => 'orders#confirmation'
    get 'thanks' => 'orders#thanks'
    get 'customers/confirmation' => 'customers#confirmation'
    patch 'customers/withdrawal' => 'customers#withdrawal'
    delete 'cart_item/destroy_all' => 'cart_items#destroy_all'
  end

  scope module: :public do
    root to: 'homes#top'
    get 'homes/about'
  end


  namespace :admin do
    resources :orders
    resources :customers
    resources :genres
    resources :items
    get '/' => 'homes#top'
    resources :order_details, only: [:update]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def customer_address
    self.postal_code + " " + self.address + " " + self.name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def sum_of_price
    item.price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  def taxin_price
    price*1.1
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, confirmation: 1, making: 2, ready: 3, sent: 4 }

  def taxin_price
    price*1.1
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { impossible: 0, waiting: 1, making: 2, completion: 3, }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    genre = Genre.new(genre_params)
    if genre.save
      redirect_to admin_genres_path
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
   if @genre.update(genre_params)
    redirect_to admin_genres_path
   end
  end

  def destroy
    @genre = Genre.find(params[:id])
    if @genre.destroy
     redirect_to admin_genres_path
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
    
  end

  def new
    @item = Item.new
    @genre = Genre.all
  end

  def create
     @item = Item.new(item_params)
     if @item.save
      redirect_to admin_item_path(@item.id)
     end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genre = Genre.all
  end

  def update
    @item = Item.find(params[:id])
   if @item.update(item_params)
    redirect_to admin_item_path(@item.id)
   end
  end

  def destroy
    @item = Item.find(params[:id])
    if @item.destroy
     redirect_to admin_items_path
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image, :genre_id)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @shipping_cost = 800
  end

  def update
      @order = Order.find(params[:id])
      @order.update(order_status)
      @order_details = @order.order_details
      if @order.status == "confirmation"
        @order_details.update_all(making_status: "waiting")
      end
      redirect_to admin_order_path
  end

  private

  def order_status
    params.require(:order).permit(:status)
  end

end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # def after_sign_in_path_for(resource)
  #   if resource == Customer
  #     public_customers_path
  #   else
  #     admin_path
  #   end

  # end

  # def after_sign_out_pash_for(resource)
  #   if admin_signed_out?
  #     new_admin_session_path
  #   end
  # end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_details_helper.rb
module Admin::OrdersDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="title">ジャンル編集</div>

<%= form_with model: @genre, url: admin_genre_path, local:true do |f| %>
<div>
<h4>ジャンル名</h4>
<%= f.text_field :name %>

<%= f.submit '変更を保存' , class:"btn btn-success" %>

</div>
<% end %>

app/views/admin/genres/index.html.erb
<div class="title">ジャンル一覧・追加</div>

<%= form_with model:@genre, url: admin_genres_path, local:true do |f| %>
  <p>ジャンル名</p>
  <%= f.text_field :name %>

  <%= f.submit"新規登録", class:"btn btn-success" %>
<% end %>

<table class="table table-hover">
  <p>ジャンル</p>

  <% @genres.each do |genre| %>
<div class="genres-list">
    　<div>
    　  <%= genre.name %>
    　</div>
  　<div>
      <%= link_to edit_admin_genre_path(genre.id), class:"btn btn-success" do %>
         編集する
      <% end %>
  　</div>
</div>
  <% end %>
</table>

app/views/admin/items/edit.html.erb
<div class="title">商品編集</div>

<div class="item-new">
  <%= form_with model: @item, url: admin_item_path, local:true do |f| %>
    <div class="new-item-list">
      <nav class="new-item">
        <p class="item">商品画像</p>
        <%= f.attachment_field :image %>
      </nav>
    </div>
    <div class="new-item-list">
      <nav class="new-item">
        <p class="item">商品名</p>
        <%= f.text_field :name %>
      </nav>
    </div>
    <div class="new-item-list">
      <nav class="new-item">
        <p class="item">商品説明</p>
        <%= f.text_field :introduction %>
      </nav>
    </div>
    <div>
      <nav class="new-item">
        <p class="item">ジャンル</p>
        <%= f.collection_select :genre_id, @genre.all, :id, :name %>
      </nav>
    </div>

    <div>
      <nav class="new-item">
        <p class="item">税抜価格</p>
        <%= f.text_field :price %>
    </div>
    <div>
      <nav class="new-item">
        <p class="item">販売ステータス</p>
          <%= f.radio_button :is_active, :TRUE %>
          <%= f.label :boolean, "販売中" %>
          <%= f.radio_button :is_active, :FALSE %>
          <%= f.label :boolean, "販売停止中" %>
      </nav>
    </div>

    <%= f.submit"変更を保存", class:"btn btn-success" %>
  <% end %>
</div>

app/views/admin/items/index.html.erb
<h2>商品一覧</h2>

<div align="right" class="admin_item_path">
<%= link_to new_admin_item_path do %>
　新商品登録
<% end %>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">商品ID</th>
      <th scope="col">商品名</th>
      <th scope="col">税抜価格</th>
      <th scope="col">ジャンル</th>
      <th scope="col">ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td scope="row"><%= item.id %></td>
        <td>
          <%= link_to item.name, admin_item_path(item.id) %>
        </td>
        <td><%= item.price %></td>
        <td><%= item.genre.name %></td>
      <% if item.is_active %>
        <td>販売中</td>
      <% else %>
        <td>販売中止</td>
      <% end %>
      </tr>
    <% end %>
  </tbody>

app/views/admin/items/new.html.erb
<div class="title">商品新規登録</div>

<div class="item-new">
  <%= form_with model: @item, url: admin_items_path, local:true do |f| %>
    <div class="new-item-list">
      <nav class="new-item">
        <p class="item">商品画像</p>
        <%= f.attachment_field :image %>
      </nav>
    </div>
    <div>
      <nav class="new-item">
        <p class="item">商品名</p>
        <%= f.text_field :name %>
      </nav>
    </div>
    <div class="new-item-list">
      <nav class="new-item">
        <p class="item">商品説明</p>
        <%= f.text_area :introduction %>
      </nav>
    </div>
    <div class="new-item-list">
      <nav class="new-item">
        <p class="item">ジャンル</p>
        <%= f.collection_select :genre_id, @genre.all, :id, :name %>
      </nav>
    </div>
    <div class="new-item-list">
      <nav class="new-item">
        <p class="item">税抜価格</p>
        <%= f.text_field :price %>
      </nav>
    </div>
    <div class="new-item-list">
      <nav class="new-item">
        <p class="item">販売ステータス</p>
          <%= f.radio_button :is_active, :TRUE %>
          <%= f.label :boolean, "販売中" %>
          <%= f.radio_button :is_active, :FALSE %>
          <%= f.label :boolean, "販売停止中" %>
      </nav>
    </div>

      <%= f.submit"新規登録", class:"btn btn-success" %>

  <% end %>
</div>

app/views/admin/items/show.html.erb
<div class="title">商品詳細</div>

<main class="main">
  <div class="item-image">
    <%= attachment_image_tag @item, :image, :size =>'300x250' %>
  </div>
<div>
  <div class="item-list">
      <li>商品名</li>
      <%= @item.name %>
  </div>
  <div class="item-list">
      <li>商品説明</li>
      <%= @item.introduction %>
  </div>
  <div class="item-list">
      <li>ジャンル</li>
      <%= @item.genre.name %>
  </div>
  <div class="item-list">
      <li>販売価格</li>
      <%= @item.price %>円
  </div>
  <div class="item-list">
      <li>販売ステータス</li>
        <% if @item.is_active %>
          <td>販売中</td>
        <% else %>
          <td>販売中止</td>
        <% end %>
        </tr>
  </div>
  <div class="item-list">
    <%= link_to '編集する', edit_admin_item_path, class:"btn btn-success" %>
  </div>
</div>
</main>

app/views/admin/orders/show.html.erb
<div class="title">注文履歴詳細</div>
<div class="admin-order-list">
  <li class="admin-order-list-item">
    <strong>購入者</strong>
  </li>
  <li class="admin-order-list-item">
    <%= @order.customer.last_name+@order.customer.first_name %>
  </li>
</div>
<div class="admin-order-list">
  <li class="admin-order-list-item">
    <strong>注文日</strong>
  </li>
  <li class="admin-order-list-item">
    <%= @order.created_at.strftime("%Y-%m-%d %H:%M") %>
  </li>
</div>
<div class="admin-order-list">
  <li class="admin-order-list-item">
    <strong>配送先</strong>
  </li>
  <li class="admin-order-list-item">
    〒<%= @order.postal_code %><%= @order.address %>
    </li>
  <li class="admin-order-list-item">
    <%= @order.name %>
  </li>
</div>
<div class="admin-order-list">
  <li class="admin-order-list-item">
    <strong>支払方法</strong>
  </li>
  <li class="admin-order-list-item">
    <%= @order.payment_method_i18n %>
  </li>
</div>
<div class="admin-order-list">
  <li class="admin-order-list-item">
    <strong>注文ステータス</strong>
  </li>
  <li class="admin-order-list-item">
    <%= form_with model: @order, url: admin_order_path, local:true do |f| %>
      <%= f.select :status, Order.statuses_i18n.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %>
      <%= f.submit "更新" , class:"btn btn-success"%>
    <% end %>
  </li>
</div>


<div>
  <table>
    <tr>
      <th>商品名</th>
      <th>単価（税込み）</th>
      <th>数量</th>
      <th>小計</th>
      <th>製作ステータス</th>
      <th></th>
    </tr>

    <% @order.order_details.each do |order_detail| %>
      <tr>
        <td><%= order_detail.item.name %></td>
        <td><%= (order_detail.price*1.1).round %>円</td>
        <td><%= order_detail.amount %></td>
        <td><%= (order_detail.price*order_detail.amount*1.1).round %>円</td>
        <td>
          <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), local:true do |f| %>
            <%= f.select :making_status, OrderDetail.making_statuses_i18n.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
            <%= f.submit "更新" , class:"btn btn-success"%>
          <% end %>
        </td>
        <td></td>
      </tr>
    <% end %>
  </table>
</div>
<div>
  <div>商品合計</div>
  <div>
    <% @sum = 0 %>
    <% @order.order_details.each do |order_detail| %>
    <div>
      <% @sum += (order_detail.price*order_detail.amount*1.1) %>
      <% end %>
      <%= @sum.round %>
    </div>
  </div>
</div>
<div>
  <div>送料</div>
  <div><%= @shipping_cost %></div>
</div>
<div>
  <div>請求金額合計</div>
  <div><%= (@sum += @shipping_cost).round %></div>
</div>