config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
  sessions:      'admins/sessions'
  # passwords:     'admins/passwords',
  # registrations: 'admins/registrations'
}
devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  # passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}


  namespace :public do
    resources :addresses
    resources :orders
    resources :cart_items
    resource :customers
    resources :items
    post 'confirmation' => 'orders#confirmation'
    get 'thanks' => 'orders#thanks'
    get 'customers/confirmation' => 'customers#confirmation'
    patch 'customers/withdrawal' => 'customers#withdrawal'
    delete 'cart_item/destroy_all' => 'cart_items#destroy_all'
  end

  scope module: :public do
    root to: 'homes#top'
    get 'homes/about'
  end


  namespace :admin do
    resources :orders
    resources :customers
    resources :genres
    resources :items
    get '/' => 'homes#top'
    resources :order_details, only: [:update]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def customer_address
    self.postal_code + " " + self.address + " " + self.name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def sum_of_price
    item.price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  def taxin_price
    price*1.1
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, confirmation: 1, making: 2, ready: 3, sent: 4 }

  def taxin_price
    price*1.1
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { impossible: 0, waiting: 1, making: 2, completion: 3, }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    genre = Genre.new(genre_params)
    if genre.save
      redirect_to admin_genres_path
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
   if @genre.update(genre_params)
    redirect_to admin_genres_path
   end
  end

  def destroy
    @genre = Genre.find(params[:id])
    if @genre.destroy
     redirect_to admin_genres_path
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
    
  end

  def new
    @item = Item.new
    @genre = Genre.all
  end

  def create
     @item = Item.new(item_params)
     if @item.save
      redirect_to admin_item_path(@item.id)
     end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genre = Genre.all
  end

  def update
    @item = Item.find(params[:id])
   if @item.update(item_params)
    redirect_to admin_item_path(@item.id)
   end
  end

  def destroy
    @item = Item.find(params[:id])
    if @item.destroy
     redirect_to admin_items_path
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image, :genre_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # def after_sign_in_path_for(resource)
  #   if resource == Customer
  #     public_customers_path
  #   else
  #     admin_path
  #   end

  # end

  # def after_sign_out_pash_for(resource)
  #   if admin_signed_out?
  #     new_admin_session_path
  #   end
  # end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-light">
        <div class="container">
          <%= link_to root_path, class: 'nav-link text-dark' do %>
            NaganoCake
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
              <nav class="header-list">
                <li class="heder-list-item">
                  <%= link_to public_customers_path do %>
                    マイページ
                  <% end %>
                </li>
                <li class="heder-list-item">
                  <%= link_to public_items_path do %>
                    商品一覧
                  <% end %>
                </li>
                <li class="heder-list-item">
                  <%= link_to public_cart_items_path do %>
                    カート
                  <% end %>
                  </li>
                <li class="heder-list-item">
                  <%= link_to destroy_customer_session_path, method: :delete do %>
                    ログアウト
                  <% end %>
                </li>
              </nav>
            <% elsif admin_signed_in? %>
              <nav class="header-list">
                <li class="heder-list-item">
                  <%= link_to admin_items_path do %>
                   商品一覧
                  <% end %>
                </li>
                <li class="heder-list-item">
                  <%= link_to admin_customers_path do %>
                    会員一覧
                  <% end %>
                </li>
                <li class="heder-list-item">
                  <%= link_to admin_path do %>
                    注文履歴一覧
                  <% end %>
                </li>
                <li class="heder-list-item">
                  <%= link_to admin_genres_path do %>
                    ジャンル一覧
                  <% end %>
                </li>
                <li class="heder-list-item">
                  <%= link_to destroy_admin_session_path, method: :delete do %>
                    ログアウト
                  <% end %>
                </li>
              </nav>
            <% else %>
              <nav class="header-list">
                <li class="heder-list-item">
                  <%= link_to homes_about_path do %>
                    About
                  <% end %>
                </li>
                <li class="heder-list-item">
                  <%= link_to public_items_path do %>
                    商品一覧
                  <% end %>
                </li>
                <li class="heder-list-item">
                  <%= link_to new_customer_registration_path do %>
                    新規登録
                  <% end %>
                </li>
                <li class="heder-list-item">
                  <%= link_to new_customer_session_path do %>
                    ログイン
                  <% end %>
                </li>
              </nav>
            <% end %>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
    <footer>
    </footer>
  </body>
</html>